apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-gateway-claim0
  name: taiga-gateway-claim0
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: taiga-gateway-vol
  resources:
    requests:
      storage: 10Gi
status: {}
