apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-static-data
  name: taiga-static-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
status: {}
