apiVersion: v1
kind: PersistentVolume
metadata:
  name: taiga-static-vol
spec:
  capacity:
    storage: 300Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /taigafileshare
    server: 10.222.14.74