apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-protected
  name: taiga-protected
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-protected
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/taiga: "true"
        io.kompose.service: taiga-protected
    spec:
      containers:
        - env:
            - name: MAX_AGE
              value: "360"
            - name: SECRET_KEY
              value: taiga-back-secret-key
          image: taigaio/taiga-protected:latest
          name: taiga-protected
          resources: {}
      restartPolicy: Always
status: {}
