apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-db
  name: taiga-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/taiga: "true"
        io.kompose.service: taiga-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: taiga
            - name: POSTGRES_PASSOWRD
              value: taiga
            - name: POSTGRES_USER
              value: taiga
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: PGDATA
              value: /var/lib/postgresql/data/pg-data
          image: postgres:12.3
          name: taiga-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: taigadb-data
      restartPolicy: Always
      volumes:
        - name: taigadb-data
          persistentVolumeClaim:
            claimName: taiga-db-data
            
status: {}
