apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-events-rabbitmq
  name: taiga-events-rabbitmq
spec:
  ports:
    - name: "7500"
      port: 7500
      targetPort: 7500
  selector:
    io.kompose.service: taiga-events-rabbitmq
status:
  loadBalancer: {}
