apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-events-rabbitmq-data
  name: taiga-events-rabbitmq-data
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: taiga-events-vol
  resources:
    requests:
      storage: 5Gi
status: {}
