apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-db-data
  name: taiga-db-data
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: taigadb-vol
  resources:
    requests:
      storage: 100Gi
status: {}
