apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-gateway
  name: taiga-gateway
spec:
  ports:
    - name: "9000"
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: taiga-gateway
status:
  loadBalancer: {}
