apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-async-rabbitmq-data
  name: taiga-async-rabbitmq-data
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: taiga-rabbit-vol
  resources:
    requests:
      storage: 3Gi
status: {}
