apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-front
  name: taiga-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/taiga: "true"
        io.kompose.service: taiga-front
    spec:
      containers:
        - env:
            - name: TAIGA_SUBPATH
            - name: TAIGA_URL
              value: http://localhost
            - name: TAIGA_WEBSOCKETS_URL
              value: ws://localhost
          image: taigaio/taiga-front:latest
          name: taiga-front
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
