apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-gateway
  name: taiga-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/taiga: "true"
        io.kompose.service: taiga-gateway
    spec:
      containers:
        - image: nginx:1.19-alpine
          name: taiga-gateway
          ports:
            - containerPort: 9000
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: taiga-gateway-vol
            - mountPath: /taiga/static
              name: taiga-static-vol
            - mountPath: /taiga/media
              name: taiga-media-vol
      restartPolicy: Always
      volumes:
        - name: taiga-gateway-vol
          persistentVolumeClaim:
            claimName: taiga-gateway-claim0
        - name: taiga-static-vol
          persistentVolumeClaim:
            claimName: taiga-static-data
        - name: taiga-media-vol
          persistentVolumeClaim:
            claimName: taiga-media-data
status: {}
