apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-media-data
  name: taiga-media-data
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: taiga-media-vol
  resources:
    requests:
      storage: 100Gi
status: {}
